query listClips($filter: ListClipsFilter){
  listClips(filter: $filter){
    items {
      ...ClipTile
    }
  }
}

fragment  ClipTile on Clip {
  id
  name
  description
  startTimecode
  endTimecode
  standard
  definition
}